### ISSUE TITLE
Nested Attributes Always require to include i18n::Alchemy

### ISSUE THREAD

**Issue by lexrupy** [carlosantoniodasilva/i18n_alchemy#26] opened 2013-05-17 20:59 UTC
When you have a model using i18n_alchemy, and have some nested association with accepts_nested_attributes, the nested is required to include i18n_alchemy, that is not desired.

**Comment by sobrinho** [comment] 2019-02-18 15:49
@juarezlustosa please research on that.

**Comment by JuarezLustosa** [comment] 2019-02-19 13:05
@carlosantoniodasilva You can close this issue. I tested here and can't reproduce this error. It is fixed.

**Comment by carlosantoniodasilva** [comment] 2019-02-19 14:27
Thanks!

**Closed by carlosantoniodasilva** 2019-02-19 14:27 UTC
